In [2]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

2026-02-01 17:44:43.823615: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-02-01 17:44:46.142922: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.


TensorFlow version: 2.20.0


In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/home/sizma86/anaconda3/lib/python3.13/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
2026-02-01 17:47:47.011199: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.01753478, -0.10205964,  0.68380344, -0.12206433, -0.26992404,
        -0.3293566 ,  0.19560575, -0.79968566, -0.12810034,  0.08911611]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.10270903, 0.09113169, 0.19997028, 0.08932675, 0.07704897,
        0.07260318, 0.12272807, 0.04536222, 0.08878919, 0.11033061]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn

<LossFunctionWrapper(<function sparse_categorical_crossentropy at 0x7f10f4379800>, kwargs={'from_logits': True, 'ignore_class': None, 'axis': -1})>

In [9]:
loss_fn(y_train[:1], predictions).numpy()

np.float32(2.6227465)

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


2026-02-01 17:52:12.516114: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:84] Allocation of 188160000 exceeds 10% of free system memory.


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9134 - loss: 0.2950
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9576 - loss: 0.1430
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - accuracy: 0.9665 - loss: 0.1103
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9737 - loss: 0.0873
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9761 - loss: 0.0774


In [12]:
model.evaluate(x_test,  y_test, verbose=2)

2026-02-01 17:53:14.334661: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:84] Allocation of 31360000 exceeds 10% of free system memory.


313/313 - 1s - 3ms/step - accuracy: 0.9746 - loss: 0.0787


[0.0787406861782074, 0.9746000170707703]

In [13]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [14]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[8.97294505e-09, 2.12683493e-09, 2.37430731e-06, 3.10131174e-04,
        8.00121011e-11, 3.80876770e-08, 6.32454362e-14, 9.99680400e-01,
        1.27450033e-08, 7.13649024e-06],
       [1.23221513e-08, 7.89293408e-05, 9.99802649e-01, 1.16918636e-04,
        7.92636650e-16, 1.73643713e-07, 8.08121854e-07, 1.85497003e-13,
        5.34663911e-07, 3.12350447e-14],
       [1.35232099e-07, 9.99322534e-01, 4.59142175e-05, 6.22473863e-06,
        4.92956569e-05, 1.68332299e-05, 1.47233013e-05, 3.54199379e-04,
        1.89468687e-04, 6.80532423e-07],
       [9.99432504e-01, 5.02646991e-08, 2.29015539e-04, 2.09097902e-06,
        9.62701051e-06, 5.12598490e-06, 7.75839726e-05, 1.81985612e-04,
        6.06852097e-07, 6.14563833e-05],
       [1.01309806e-05, 1.19043833e-08, 2.64320715e-06, 1.90452520e-09,
        9.99549687e-01, 2.23044117e-09, 1.42129011e-06, 3.04334444e-05,
        1.36736460e-07, 4.05519677e-04]], dtype=float32)>